services:
  mysql-master:
    image: mysql:8.3
    container_name: mysql-master
    command: --server-id=1 --log-bin=mysql-bin --binlog-format=row
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: sakila
#      MYSQL_USER: replication_user
#      MYSQL_PASSWORD: 654321
    ports:
      - "3306:3306"
    networks:
      - replication-network

  mysql-slave:
    image: mysql:8.3
    container_name: mysql-slave
    depends_on:
      - mysql-master
    command: --server-id=2 --log-bin=mysql-bin --binlog-format=row --read-only=1
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: sakila
#      MYSQL_USER: replication_user
#      MYSQL_PASSWORD: 654321
    ports:
      - "3307:3306"
    networks:
      - replication-network

networks:
  replication-network:
    driver: bridge
